"""Generate markdown documentation per ticket."""

import json
from datetime import datetime
from typing import Optional

from app.paths import DOCS_DIR, ensure_dirs
from app.db.model import SessionLocal, Ticket, GeneratedContent
from app.logic.related_tickets import find_related_tickets


def generate_ticket_doc(ticket_id: str) -> Optional[str]:
    """
    Generate a markdown documentation file for a ticket.

    Args:
        ticket_id: The ID of the ticket to document

    Returns:
        Path to the generated file, or None if ticket not found
    """
    ensure_dirs()

    session = SessionLocal()
    ticket = session.query(Ticket).filter_by(id=ticket_id).first()

    if not ticket:
        session.close()
        return None

    # Get generated content
    content_items = session.query(GeneratedContent).filter_by(
        ticket_id=ticket_id
    ).all()

    questions = []
    test_cases = []
    for item in content_items:
        try:
            data = json.loads(item.content)
            if item.content_type == 'questions':
                questions = data
            elif item.content_type == 'test_cases':
                test_cases = data
        except json.JSONDecodeError:
            pass

    session.close()

    # Get related tickets
    related = find_related_tickets(ticket_id, threshold=0.75, top_k=5)

    # Build markdown content
    lines = [
        f"# {ticket.jira_key} - {ticket.title}",
        "",
        f"**Type:** {ticket.issue_type}",
        f"**Status:** {ticket.status}",
        f"**Last Updated:** {ticket.updated_at.strftime('%Y-%m-%d %H:%M') if ticket.updated_at else 'N/A'}",
        "",
        "## Description",
        "",
        ticket.description or "_No description provided._",
        "",
    ]

    # Add questions section
    lines.append("## Refinement Questions")
    lines.append("")
    if questions:
        for q in questions:
            lines.append(f"- {q}")
    else:
        lines.append("_No questions generated yet._")
    lines.append("")

    # Add test cases section
    lines.append("## Test Cases")
    lines.append("")
    if test_cases:
        for tc in test_cases:
            lines.append(tc)
    else:
        lines.append("_No test cases generated yet._")
    lines.append("")

    # Add related tickets section
    lines.append("## Related Tickets")
    lines.append("")
    if related:
        for rel_ticket, score in related:
            lines.append(f"- [{rel_ticket.jira_key}]({rel_ticket.jira_key}.md): {rel_ticket.title} ({score:.0%} similar)")
    else:
        lines.append("_No closely related tickets found._")
    lines.append("")

    # Add generation timestamp
    lines.append("---")
    lines.append(f"_Generated by ProRef on {datetime.now().strftime('%Y-%m-%d %H:%M')}_")

    # Write to file
    doc_path = DOCS_DIR / f"{ticket.jira_key}.md"
    doc_path.write_text("\n".join(lines), encoding="utf-8")

    return str(doc_path)


def generate_all_docs() -> int:
    """
    Generate documentation for all tickets.

    Returns:
        Number of documents generated
    """
    session = SessionLocal()
    tickets = session.query(Ticket).all()
    session.close()

    count = 0
    for ticket in tickets:
        path = generate_ticket_doc(ticket.id)
        if path:
            count += 1

    return count
